spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      #        show_sql: true
        format_sql: true
        default_schema: jpa
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace